version: "3.9"

services:
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    command: mongod --auth # Require authentication
    volumes:
      - ./mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: changethisuser
      MONGO_INITDB_ROOT_PASSWORD: changethispass
      MONGO_INITDB_DATABASE: data
      MONGO_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    ports:
      - 28017:27017 # In case the user has an instance of mongo already running on 27017

volumes:
  mongodata:
